export const videoPlayerActionTypes = {
  SET_CURRENT_VIDEO_PLAY_TIME: 'SET_CURRENT_VIDEO_PLAY_TIME',
  SET_VIDEO_DURATION: 'SET_VIDEO_DURATION',
  SET_VIDEO_PLAYER_OBJECT: 'SET_VIDEO_PLAYER_OBJECT',
};
