import {
  DEV_WEBCLIENTID,
  DEV_APIKEY,
  DEV_AUTHDOMAIN,
  DEV_PROJECTID,
  DEV_STORAGEBUCKET,
  DEV_MESAGINGSENDERID,
  DEV_APPID,
  DEV_MEASUREMENTID,
} from '@env';

const devEnvironmentVariables = {
  DEV_WEBCLIENTID,
  DEV_APIKEY,
  DEV_AUTHDOMAIN,
  DEV_PROJECTID,
  DEV_STORAGEBUCKET,
  DEV_MESAGINGSENDERID,
  DEV_APPID,
  DEV_MEASUREMENTID,
};

export default devEnvironmentVariables;
