export const actionTypes = {
  SET_FULLSCREEN_VIDEO: 'SET_FULLSCREEN_VIDEO',
  SET_CURRENT_VIDEO_PLAY_TIME: 'SET_CURRENT_VIDEO_PLAY_TIME',
  TOGGLE_PAUSE_VIDEO: 'TOGGLE_PAUSE_VIDEO',
  SET_OVERLAY_VIEW: 'SET_OVERLAY_VIEW',
  SET_SCREEN_DIMENSIONS: 'SET_SCREEN_DIMENSIONS',
  SET_VIDEO_DURATION: 'SET_VIDEO_DURATION',
};
