export const actionTypes = {
  SET_FULLSCREEN_VIDEO: 'SET_FULLSCREEN_VIDEO',
  TOGGLE_PAUSE_VIDEO: 'TOGGLE_PAUSE_VIDEO',
  SET_OVERLAY_VIEW: 'SET_OVERLAY_VIEW',
  SET_SCREEN_DIMENSIONS: 'SET_SCREEN_DIMENSIONS',
};
